kerala_food = {
   "breakfast": {
      "base_items": {
        "core_items": [
          "Idli",
          "Dosa",
          "Masala Dosa",
          "Ghee Roast Dosa",
          "Rava Dosa",
          "Wheat Dosa",
          "Ragi Dosa",
          "Neer Dosa",
          "Onion Uthappam",
          "Plain Uthappam",
          "Appam",
          "Idiyappam",
          "Puttu",
          "Pathiri",
          "Parotta",
          "Poori",
          "Chapati",
          "Roti",
          "Bread",
          "Pav"
        ],
        "complete_dishes": [
          "Upma",
          "Semiya Upma",
          "Aval Upma",
          "Pongal",
          "Ela Ada",
          "Kappa",
          "Banana"
        ]
      },
      "veg_items": {
        "gravy": [
          "Vegetable Stew",
          "Kadala Curry", 
          "Sambar",
          "Coconut Chutney",
          "Tomato Chutney",
          "Mint Chutney",
          "Potato Masala",
          "Chana Curry",
          "Coconut Milk",
          "Mulaku Chammanthi",
          "Kappa Puzhukku",
          "Thari Kanji",
          "Vendakka Stew",
          "Kumbalanga Stew",
          "Kappa Vevichathu",
          "Red Chilli Chutney",
          "Pazham Kanji",
          "Coconut Milk Kanji",
          "Uluva Kanji",
          "Vegetable Kurma",
          "Avial"
        ]
      },
      "non_veg_items": {
        "gravy": [
          "Chicken Stew",
          "Egg Curry",
          "Fish Curry",
          "Chicken Curry",
          "Egg Roast",
          "Egg Dosa",
          "Egg Appam",
          "Mutta Roast",
          "Mutta Curry",
          "Fish Molee",
          "Chemmeen Roast",
          "Prawns Stew",
          "Chicken Kurma",
          "Egg Masala"
        ]
      }
    },

    "lunch": {
      "base_items": [
        "Rice",
        "Brown Rice",
        "Steamed Rice",
        "Basmati Rice",
        "Jeera Rice",
        "Ghee Rice",
        "Kaima Rice",
        "Neychoru",
        "Tomato Rice",
        "Lemon Rice",
        "Curd Rice",
        "Tamarind Rice",
        "Coconut Milk Rice",
        "Fried Rice",
        "Pulao",
        "Biryani",
        "Vegetable Biryani",
        "Thalassery Veg Biryani",
        "Chapati",
        "Roti",
        "Parotta",
        "Pathiri"
      ],
      "veg_items": [
        "Kerala Sadya",
        "Sambar",
        "Rasam",
        "Moru Curry",
        "Avial",
        "Thoran",
        "Olan",
        "Kalan",
        "Erissery",
        "Pachadi",
        "Inji Curry",
        "Theeyal",
        "Koottu Curry",
        "Pulissery",
        "Parippu Curry",
        "Coconut Chammanthi",
        "Bitter Gourd Theeyal",
        "Ash Gourd Pulissery",
        "Long Beans Thoran",
        "Cabbage Thoran",
        "Beetroot Pachadi",
        "Okra Curry",
        "Tomato Rasam",
        "Ulli Theeyal",
        "Drumstick Curry",
        "Jackfruit Erissery",
        "Pumpkin Curry",
        "Mango Pulissery",
        "Chena Mezhukkupuratti",
        "Kovakka Thoran",
        "Payar Mezhukkupuratti",
        "Koorka Fry",
        "Kaya Mezhukkupuratti",
        "Vegetable Roast",
        "Vegetable Ishtu",
        "Raw Mango Curry",
        "Dal Fry",
        "Veg Manchurian",
        "Vegetable Kurma",
        "Vegetable Stew",
        "Kadala Curry",
        "Banana Chips",
        "Sharkkara Upperi"
      ],
      "non_veg_items": [
        "Kerala Fish Curry",
        "Meen Pollichathu",
        "Meen Vevichathu",
        "Fish Fry",
        "Sardine Curry",
        "Ayala Curry",
        "King Fish Fry",
        "Crab Roast",
        "Prawns Curry",
        "Prawns Roast",
        "Prawns Masala",
        "Kanava Roast",
        "Kanava Thoran",
        "Mussel Fry",
        "Chicken Roast",
        "Chicken Curry",
        "Nadan Kozhi Curry",
        "Chicken Varattiyathu",
        "Pepper Chicken Roast",
        "Chicken Chettinad",
        "Chicken Fry",
        "Mutton Curry",
        "Mutton Stew",
        "Mutton Varattiyathu",
        "Beef Ularthiyathu",
        "Beef Roast",
        "Beef Fry",
        "Duck Roast",
        "Duck Curry",
        "Egg Curry",
        "Egg Roast",
        "Mutta Thoran",
        "Thalassery Chicken Biryani",
        "Malabar Mutton Biryani",
        "Fish Biryani",
        "Prawns Biryani",
        "Egg Biryani",
        "Chicken Manchurian",
        "Fish Molee",
        "Mutton Fry"
      ]
    },

    "dinner": {
      "base_items": [
        "Rice",
        "Brown Rice",
        "Steamed Rice",
        "Basmati Rice",
        "Jeera Rice",
        "Ghee Rice",
        "Neychoru",
        "Coconut Milk Rice",
        "Fried Rice",
        "Pulao",
        "Biryani",
        "Chapati",
        "Roti",
        "Parotta",
        "Kerala Parotta",
        "Pathiri",
        "Kothu Parotta"
      ],
      "veg_items": [
        "Vegetable Kurma",
        "Vegetable Stew",
        "Vegetable Ishtu",
        "Chammanthi",
        "Chakka Puzhukku",
        "Chutney",
        "Kadala Curry",
        "Tomato Kurma",
        "Vegetable Masala",
        "Mint Chutney",
        "Potato Curry",
        "Dal Fry",
        "Vegetable Fried Rice",
        "Paneer Masala",
        "Vegetable Cutlet",
        "Thoran",
        "Pumpkin Curry",
        "Bitter Gourd Fry",
        "Cabbage Thoran",
        "Beans Mezhukkupuratti",
        "Drumstick Leaves Thoran",
        "Carrot Thoran",
        "Beetroot Curry",
        "Cucumber Pachadi",
        "Mango Curry",
        "Raw Banana Fry",
        "Veg Roll",
        "Mushroom Curry",
        "Mushroom Thoran",
        "Paneer Butter Masala",
        "Baby Corn Kurma",
        "Corn & Peas Pulao",
        "Soya Chunk Curry",
        "Soya Thoran",
        "Pineapple Pulissery",
        "Chena Theeyal",
        "Nenthra Pazham Curry",
        "Vendakka Masala",
        "Ela Ada (Light dinner)"
      ],
      "non_veg_items": [
        "Chicken Curry",
        "Chicken Roast",
        "Chicken Stew",
        "Chicken Fried Rice",
        "Chicken 65",
        "Chicken Chukka",
        "Chicken Kothu",
        "Beef Fry",
        "Beef Roast",
        "Beef Curry",
        "Beef Stew",
        "Beef Kothu",
        "Mutton Curry",
        "Mutton Stew",
        "Mutton Fry",
        "Mutton Ularthiyathu",
        "Mutton Kothu",
        "Fish Molee",
        "Fish Fry",
        "Meen Vevichathu",
        "Fish Molly",
        "Squid Roast",
        "Kanava Curry",
        "Mussel Fry",
        "Egg Curry",
        "Egg Roast",
        "Egg Masala",
        "Egg Kurma",
        "Egg Fried Rice",
        "Egg Kothu",
        "Prawns Fried Rice",
        "Prawns Masala Wrap",
        "Chicken Wrap",
        "Fish Wrap",
        "Egg Wrap",
        "Duck Roast",
        "Duck Curry"
      ]
    }
}
