snacks = {
    "healthy_snacks": [
        "Apple slices",
        " peanut butter",
        "Carrot sticks ",
        "hummus",
        "Banana",
        "almond butter",
        "Celery sticks ",
        "Sliced cucumber ",
        "Greek yogurt dip",
        "Mixed berries (blueberries, strawberries, raspberries)",
        "Sliced pear ",
        "ricotta",
        "Cherry tomatoes ",
        "balsamic glaze",
        "Steamed edamame with",
        "sea salt",
        "Avocado on rice cakes",
        "Greek yogurt ",
        "honey ",
        "granola",
        "Cottage cheese",
        "pineapple",
        "Cheese cubes",
        "whole-grain crackers",
        "Skyr (Icelandic yogurt)",
        "berries",
        "String cheese",
        "almonds",
        "Low-fat milk smoothie",
        "banana",
        "Almonds ",
        " dark chocolate chips",
        "Trail mix (nuts, seeds, dried fruit)",
        "Peanut butter on whole-wheat toast",
        "Chia seed pudding ",
        "almond milk",
        "Sunflower seeds",
        "dried cranberries",
        "Dates stuffed",
        "almond butter",
        "Walnuts with apple slices",
        "Flaxseed crackers",
        "Cashew butter",
        "banana slices",
        "Oatmeal ",
        "cinnamon",
        "berries",
        "Popcorn (air-popped",
        "light seasoning)",
        "Roasted chickpeas",
        "Mini whole-wheat wraps",
        "veggies",
        "Quinoa salad cups",
        "Lentil soup in a mug",
        "Whole-grain toast ",
        "mashed avocado",
        "Brown rice cakes ",
        "cottage cheese",
        "Muesli ",
        "almond milk",
        "Sweet potato toast (sliced, toasted sweet potato)",
        "Protein balls (oats, peanut butter, honey)",
        "Dark chocolate-dipped strawberries", 
        "Fruit and nut bars (like Larabars)",
        "Smoothie bowl ",
        "seeds and fruits",
        "No-bake energy bites",
        "Greek yogurt and matcha parfait",
        "Cold oatmeal ",
        "fruit (overnight oats)",
        "Watermelon cubes ",
        "feta ",
        "mint",
        "Baked zucchini chips ",
        "yogurt dip"
    ],
    "veg_snacks": [
        "Sprouts Salad",
        "Fruit Bowl",
        "Vegetable Salad",
        "Cucumber",
        " Carrot Sticks",
        "Tender Coconut",
        "Peanut Chikki",
        "Roasted Peanuts",
        "Roasted Chana",
        "Dry Fruits Mix",
        "Trail Mix (Nuts + Seeds)",
        "Fox Nuts (Makhana)",
        "Wheat Rusk",
        "Oats Biscuit",
        "Millet Ladoo",
        "Millet Chips",
        "Khakhra",
        "Dhokla",
        "Poha Chivda (Low Oil)",
        "Popcorn (Air-popped)",
        "Veg Sandwich (Whole Wheat, Low Oil)",
        "Peanut Butter Sandwich",
        "Wheat Crackers",
        "Moong Dal Chilla",
        "Besan Chilla",
        "Soya Chunks (Roasted)",
        "Paneer Tikka",
        "Tofu Stir Fry",
        "Greek Yogurt Cup",
        "Sprouted Moong Bowl"
    ],
    "non_veg_snacks": [
        "Boiled Eggs",
        "Omelette",
        "Egg Bhurji",
        "Egg Sandwich",
        "Chicken Sandwich",
        "Chicken Cutlet (Low Oil)",
        "Grilled Chicken Strips",
        "Chicken Sausage (Low Fat)",
        "Tuna Sandwich",
        "Fish Cutlet (Low Oil)",
        "Prawn Salad Bowl"
    ],
    "beverages": {
       
        "moderate_calories": [
            "Tender Coconut Water",
            "Buttermilk (Chaas)",
            "Salted Lassi",
            "Fresh Lime Soda (without sugar)",
            "Masala Chai (less sugar)",
            "Hot Chocolate (light)",
            "Badam Milk (light version)",
            "Protein Shake (Whey/Plant Protein)",
            "Cold Coffee (low sugar)",
            "Fruit Smoothie (Banana, Papaya, Berry, low sugar)",
            "Milk (Hot/Cold)",
            "Turmeric Milk (Haldi Milk)"
        ]
    }
}
