western_food = {
    "breakfast": {
        "base_items": {
            "core_items": [
                "Toast",
                "White Bread",
                "Whole Wheat Bread",
                "Sourdough Bread",
                "Bagel",
                "English Muffin",
                "Croissant",
                "Pancakes",
                "Waffles",
                "French Toast",
                "Hash Browns",
                "Home Fries",
                "Breakfast Potatoes",
                "Scrambled Eggs",
                "Fried Eggs",
                "Poached Eggs",
                "Boiled Eggs",
                "Omelette",
                "Eggs Benedict",
                "Breakfast Burrito",
                "Breakfast Sandwich",
                "Granola",
                "Cereal",
                "Oatmeal",
                "Porridge",
                "Yogurt",
                "Greek Yogurt"
            ],
            "complete_dishes": [
                "Full English Breakfast",
                "Continental Breakfast",
                "American Breakfast",
                "Breakfast Bowl",
                "Avocado Toast",
                "Eggs on Toast",
                "Breakfast Wrap"
            ]
        },
        "veg_items": {
            "gravy": [
                "Hollandaise Sauce",
                "Maple Syrup",
                "Honey",
                "Jam",
                "Marmalade",
                "Peanut Butter",
                "Almond Butter",
                "Cream Cheese",
                "Butter",
                "Fruit Compote",
                "Berry Sauce",
                "Hollandaise Sauce (Veg)"
            ]
        },
        "non_veg_items": {
            "gravy": [
                "Bacon",
                "Sausages",
                "Ham",
                "Canadian Bacon",
                "Turkey Sausage",
                "Chicken Sausage",
                "Smoked Salmon",
                "Eggs Benedict with Ham",
                "Breakfast Sausage Gravy",
                "Bacon Gravy"
            ]
        }
    },

    "lunch": {
        "base_items": {
            "core_items": [
                "Sandwich Bread",
                "Whole Wheat Bread",
                "Sourdough Bread",
                "Rye Bread",
                "Ciabatta",
                "Focaccia",
                "Baguette",
                "Wrap",
                "Tortilla",
                "Pita Bread",
                "Burger Bun",
                "Hot Dog Bun",
                "Rice",
                "Pasta",
                "Spaghetti",
                "Penne",
                "Fusilli",
                "Macaroni",
                "Fettuccine",
                "Linguine",
                "Risotto",
                "Quinoa",
                "Couscous",
                "Salad Greens",
                "Mixed Greens",
                "Lettuce",
                "Spinach",
                "Arugula"
            ],
            "complete_dishes": [
                "Caesar Salad",
                "Greek Salad",
                "Cobb Salad",
                "Garden Salad",
                "Chef Salad",
                "Waldorf Salad",
                "Pasta Salad",
                "Quinoa Salad",
                "Couscous Salad",
                "Soup and Salad",
                "Sandwich Combo",
                "Burger Combo"
            ]
        },
        "veg_items": {
            "dry": [
                "Grilled Vegetables",
                "Roasted Vegetables",
                "Vegetable Skewers",
                "Stuffed Bell Peppers",
                "Vegetable Fritters",
                "Zucchini Fritters",
                "Corn Fritters",
                "Vegetable Tempura",
                "Fried Zucchini",
                "Breaded Mushrooms",
                "Onion Rings",
                "French Fries",
                "Sweet Potato Fries",
                "Hash Browns",
                "Vegetable Chips"
            ],
            "gravy": [
                "Vegetable Soup",
                "Tomato Soup",
                "Minestrone",
                "Cream of Mushroom Soup",
                "Broccoli Cheddar Soup",
                "Vegetable Stew",
                "Ratatouille",
                "Pasta Primavera",
                "Vegetable Lasagna",
                "Eggplant Parmesan",
                "Vegetable Risotto",
                "Mac and Cheese",
                "Alfredo Pasta",
                "Marinara Pasta",
                "Pesto Pasta",
                "Vegetable Curry (Western Style)",
                "Vegetable Stir Fry",
                "Vegetable Casserole",
                "Stuffed Bell Peppers (Gravy)",
                "Vegetable Pot Pie",
                "Vegetable Shepherd's Pie"
            ]
        },
        "non_veg_items": {
            "dry": [
                "Grilled Chicken",
                "Fried Chicken",
                "Chicken Wings",
                "Chicken Tenders",
                "Chicken Nuggets",
                "Grilled Fish",
                "Fried Fish",
                "Fish and Chips",
                "Grilled Salmon",
                "Tuna Steak",
                "Shrimp Skewers",
                "Grilled Shrimp",
                "Fried Shrimp",
                "Calamari",
                "Chicken Sandwich",
                "Turkey Sandwich",
                "Ham Sandwich",
                "Tuna Sandwich",
                "Chicken Burger",
                "Turkey Burger",
                "Fish Burger",
                "Chicken Wrap",
                "Turkey Wrap",
                "Tuna Wrap"
            ],
            "gravy": [
                "Chicken Soup",
                "Chicken Noodle Soup",
                "Cream of Chicken Soup",
                "Beef Stew",
                "Chicken Stew",
                "Seafood Chowder",
                "Clam Chowder",
                "Fish Chowder",
                "Chicken Pot Pie",
                "Beef Pot Pie",
                "Shepherd's Pie",
                "Chicken Casserole",
                "Tuna Casserole",
                "Chicken Alfredo",
                "Chicken Pasta",
                "Seafood Pasta",
                "Shrimp Scampi",
                "Chicken Risotto",
                "Seafood Risotto",
                "Chicken Curry (Western Style)",
                "Beef Stroganoff",
                "Chicken Stroganoff",
                "Coq au Vin",
                "Chicken Marsala",
                "Chicken Piccata",
                "Fish Curry (Western Style)",
                "Lobster Bisque",
                "Crab Bisque"
            ]
        }
    },

    "dinner": {
        "base_items": {
            "core_items": [
                "Mashed Potatoes",
                "Baked Potato",
                "Roasted Potatoes",
                "French Fries",
                "Sweet Potato",
                "Rice",
                "Wild Rice",
                "Brown Rice",
                "Pasta",
                "Spaghetti",
                "Penne",
                "Fettuccine",
                "Linguine",
                "Rigatoni",
                "Risotto",
                "Quinoa",
                "Couscous",
                "Polenta",
                "Bread",
                "Garlic Bread",
                "Dinner Rolls",
                "Biscuits"
            ],
            "complete_dishes": [
                "Pizza",
                "Margherita Pizza",
                "Vegetable Pizza",
                "Pepperoni Pizza",
                "Chicken Pizza",
                "BBQ Chicken Pizza",
                "Hawaiian Pizza",
                "Lasagna",
                "Vegetable Lasagna",
                "Chicken Lasagna",
                "Beef Lasagna",
                "Spaghetti and Meatballs",
                "Fettuccine Alfredo",
                "Pasta Carbonara",
                "Penne Arrabbiata"
            ]
        },
        "veg_items": {
            "dry": [
                "Grilled Vegetables",
                "Roasted Vegetables",
                "Steamed Vegetables",
                "Sautéed Vegetables",
                "Vegetable Medley",
                "Asparagus",
                "Broccoli",
                "Brussels Sprouts",
                "Green Beans",
                "Carrots",
                "Cauliflower",
                "Zucchini",
                "Eggplant",
                "Mushrooms",
                "Stuffed Bell Peppers",
                "Vegetable Skewers",
                "Ratatouille",
                "Caprese Salad",
                "Greek Salad"
            ],
            "gravy": [
                "Vegetable Risotto",
                "Mushroom Risotto",
                "Vegetable Pasta",
                "Pasta Primavera",
                "Vegetable Lasagna",
                "Eggplant Parmesan",
                "Vegetable Casserole",
                "Vegetable Pot Pie",
                "Vegetable Shepherd's Pie",
                "Vegetable Stew",
                "Ratatouille",
                "Vegetable Curry (Western Style)",
                "Vegetable Stir Fry",
                "Creamed Spinach",
                "Creamed Corn",
                "Green Bean Casserole",
                "Mac and Cheese",
                "Alfredo Pasta",
                "Marinara Pasta",
                "Pesto Pasta",
                "Aglio e Olio",
                "Vegetable Soup",
                "Minestrone",
                "Tomato Basil Soup",
                "Broccoli Cheddar Soup"
            ]
        },
        "non_veg_items": {
            "dry": [
                "Grilled Steak",
                "Pan-Seared Steak",
                "Filet Mignon",
                "Ribeye Steak",
                "Sirloin Steak",
                "T-Bone Steak",
                "Porterhouse Steak",
                "Grilled Chicken Breast",
                "Roasted Chicken",
                "Fried Chicken",
                "Chicken Wings",
                "Grilled Salmon",
                "Pan-Seared Salmon",
                "Baked Salmon",
                "Grilled Tuna",
                "Pan-Seared Tuna",
                "Grilled Shrimp",
                "Pan-Seared Shrimp",
                "Grilled Scallops",
                "Pan-Seared Scallops",
                "Lobster Tail",
                "Crab Legs",
                "Roast Beef",
                "Prime Rib",
                "Beef Tenderloin",
                "Lamb Chops",
                "Pork Chops",
                "Grilled Pork",
                "BBQ Ribs",
                "Chicken Thighs",
                "Drumsticks",
                "Turkey Breast",
                "Duck Breast"
            ],
            "gravy": [
                "Beef Stew",
                "Chicken Stew",
                "Lamb Stew",
                "Coq au Vin",
                "Beef Bourguignon",
                "Chicken Marsala",
                "Chicken Piccata",
                "Chicken Cordon Bleu",
                "Chicken Parmesan",
                "Chicken Alfredo",
                "Chicken Pasta",
                "Seafood Pasta",
                "Shrimp Scampi",
                "Lobster Pasta",
                "Crab Pasta",
                "Chicken Risotto",
                "Seafood Risotto",
                "Mushroom Risotto with Chicken",
                "Chicken Pot Pie",
                "Beef Pot Pie",
                "Shepherd's Pie",
                "Chicken Casserole",
                "Tuna Casserole",
                "Beef Stroganoff",
                "Chicken Stroganoff",
                "Chicken Curry (Western Style)",
                "Beef Curry (Western Style)",
                "Fish Curry (Western Style)",
                "Seafood Chowder",
                "Clam Chowder",
                "Lobster Bisque",
                "Crab Bisque",
                "Chicken Noodle Soup",
                "Beef Soup",
                "French Onion Soup",
                "Chicken Fricassee",
                "Beef Ragu",
                "Osso Buco",
                "Braised Short Ribs",
                "Chicken Tagine",
                "Lamb Tagine"
            ]
        }
    }
}
